### PR TITLE
Bumped Java codemodder to 0.70.3

### PR DESCRIPTION
**Pull request by nahsra**
This should fix some of the hanging we've seen on projects.

### CODE REVIEW

**Review by matt- — APPROVED** [review]
LGTM

**Comment by nahsra** [comment]
This doesn't fix the issue I hoped it might. Might have to do another release and re-open with a new version.

**Comment by matt-** [comment]
Just ran: 

```
git checkout bump-codemodder-ver
brew reinstall -v  ./Formula/homebrew/pixee-java-codemods.rb
```

Then checked pixee-java-codemods and confirmed that it is `codemodder: java/0.70.3`

**Comment by nahsra** [comment]
Tested this locally and confirmed basic functions work.

**Pull request merged**
